[build]
  command = "ng build:ssr && ng run alyteq-front:server"
  publish = "dist/alyteq-front/browser"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[functions]]
  directory = "dist/alyteq-front/server"
  external_node_modules = ["@angular/ssr"]
